// This file is auto-generated by Figma Make
// Get Supabase credentials from __FIGMA_MAKE__ global or environment

declare global {
  interface Window {
    __FIGMA_MAKE__?: {
      supabase?: {
        projectId?: string;
        publicAnonKey?: string;
      };
    };
  }
}

// Try to get from global first, fallback to extracting from existing client
export const projectId =
  (typeof window !== 'undefined' && window.__FIGMA_MAKE__?.supabase?.projectId) ||
  'zfzwknmljpotidwyoefk';

export const publicAnonKey =
  (typeof window !== 'undefined' && window.__FIGMA_MAKE__?.supabase?.publicAnonKey) ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmendrbm1sanBvdGlkd3lvZWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODQxNTMsImV4cCI6MjA4NTM2MDE1M30.zz_eMP7Xg04HI69y0sgpQzs4osujmMJ1Dt6fkDwLvPI';
