// This file is auto-generated by Figma Make
// Get Supabase credentials from __FIGMA_MAKE__ global or environment

declare global {
  interface Window {
    __FIGMA_MAKE__?: {
      supabase?: {
        projectId?: string;
        publicAnonKey?: string;
      };
    };
  }
}

// Try to get from global first, fallback to extracting from existing client
export const projectId =
  (typeof window !== 'undefined' && window.__FIGMA_MAKE__?.supabase?.projectId) ||
  'ikgostf4f7x25n4op5tf4lsidaltob55znnfax3gono7d4h7kzql';

export const publicAnonKey =
  (typeof window !== 'undefined' && window.__FIGMA_MAKE__?.supabase?.publicAnonKey) ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZ29zdGY0Zjd4MjVuNG9wNXRmNGxzaWRhbHRvYjU1em5uZmF4M2dvbm83ZDRoN2t6cWwiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc0MzYzNzUyNywiZXhwIjoyMDU5MjEzNTI3fQ.yOiSvbRKJhfP-twPXnFbp8B3l84Gl98sN7ZrOk0UthY';
